# Generated by Django 4.1.1 on 2025-01-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorgeneral',
            options={'verbose_name_plural': 'Director Generals'},
        ),
    ]
